{{- if $.Values.githubApp.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "renovate.fullname" . }}-github-app
type: Opaque
data:
  GITHUB_APP_ID: "{{ $.Values.githubApp.id | required "A GitHub App ID is required (githubApp.id)" | b64enc }}"
  GITHUB_APP_INSTALL_ID: "{{ $.Values.githubApp.installId | required "A GitHub App install ID is required (githubApp.installId)" | b64enc }}"
  GITHUB_APP_PRIVATE_KEY: "{{ $.Values.githubApp.privateKey | required "A GitHub App private key is required (githubApp.privateKey)" | b64enc }}"
{{- end }}
